variables:
  CI_IMAGE: $REGISTRY/$REGISTRY_USER/$CI_PROJECT_NAME
  CI_BUILD_ARCHS: linux/amd64,linux/arm64,linux/arm/v7

stages:
  - lint
  - build
  - push

hadolint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint
        --ignore DL3008
        Dockerfile

.before_script_template:
  before_script:
    - echo -n $REGISTRY_TOKEN | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use

.build-image: &build-image
  extends: .before_script_template
  image: jdrouet/docker-with-buildx:latest
  stage: build
  except:
    - master
  services:
    - docker:dind
  script:
    - docker buildx build
      --platform "$CI_BUILD_ARCHS"
      --cache-from "$CI_IMAGE"
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg RELEASE=$RELEASE
      --pull --tag "$CI_IMAGE:$CI_COMMIT_REF_SLUG" .

.push-image: &push-image
  extends: .before_script_template
  image: jdrouet/docker-with-buildx:latest
  stage: push
  only:
    - master
  services:
    - docker:dind
  script:
    - docker buildx build
      --platform "$CI_BUILD_ARCHS"
      --cache-from "$CI_IMAGE"
      --build-arg BUILDKIT_INLINE_CACHE=1
      --build-arg RELEASE=$TAG_NAME
      --pull --tag "$CI_IMAGE:$TAG_NAME" --push .

###########
# LMS 8.1 #
###########

#build 8.1:
#  <<: *build-image
#  variables:
#    RELEASE: "8.1"
#
#push 8.1:
#  <<: *push-image
#  variables:
#    TAG_NAME: "8.1"

###########
# LMS 8.2 #
###########

build 8.2:
  <<: *build-image
  variables:
    RELEASE: "8.2"

push 8.2:
  <<: *push-image
  variables:
    TAG_NAME: "8.2"
